# ==============================
# --- Physics list settings ---
# ==============================



# Read your GDML detector description
/detector/readGDML gdml/MAIA_v0.gdml

# JTR: Have to initialize the run before the gun with the new biasing
/run/initialize

#/physics_lists/em/addNeutrino


# Set detector name first, BEFORE initializing physics list

# Activate neutrino physics
#/physics_lists/em/NuETotXscActivation true
#/physics_lists/em/NeETotXscActivation true

# Set neutrino bias factors

# ==============================
# --- Primary particle gun ---
# ==============================
/gun/particle e-
/gun/energy 20 GeV
/gun/direction 0 0 1
/gun/position 0 0 10 cm


# ==============================
# --- Run ---
# ==============================
/run/printProgress 100
#/tracking/storeTrajectory 0
#/tracking/verbose 2       # Increase tracking verbosity
#/process/verbose 2        # Process-level verbosity
#/run/verbose 1



/run/beamOn 10




# EM / other processes
#/physics_lists/em/SyncRadiation true
#/physics_lists/em/SyncRadiationAll true
#/physics_lists/em/GammaNuclear true
#/physics_lists/em/UseGammaNuclearXS false
#/physics_lists/em/LENDGammaNuclear false
#/physics_lists/em/ElectroNuclear true
#/physics_lists/em/MuonNuclear false
#/physics_lists/em/GammaToMuons false
#/physics_lists/em/PositronToMuons true
#/physics_lists/em/PositronToHadrons true

# Optional conversion factors (uncomment to use)
#/physics_lists/em/GammaToMuonsFactor 1.0
#/physics_lists/em/PositronToMuonsFactor 1.0
#/physics_lists/em/PositronToHadronsFactor 1.0

# ==============================
# --- Visualization ---
# ==============================
#/vis/open OGL
#/vis/viewer/set/viewpointThetaPhi 90 180
#/vis/scene/add/trajectories
#/vis/scene/add/axes 0 0 0 10 cm
